- .gitignore
- Package.swift
- Sources/WebSocket/WebSocket+Client.swift
- Sources/WebSocket/WebSocket+Server.swift
- Sources/WebSocket/WebSocket.swift
- Sources/WebSocket/WebSocketHandler.swift
- Tests/WebSocketTests/WebSocketTests.swift
> add support for websocket close code; other bug fixes

- Sources/WebSocket/WebSocketHandler.swift
Currently, WebSocket client does not handle inbound message correctly. It takes only **first `n` bytes** , as a result, the client received a **broken** message (by default it approximately 1024 bytes, but it depends on server configuration). A big number of servers support fragmentation e.g. [gorilla/websocket](https://github.com/gorilla/websocket).
> In the WebSocket Protocol, data is transmitted using a sequence of
frames.  
The base framing protocol defines a frame type with an opcode, a
payload length, and designated locations for "Extension data" and
"Application data", which together define the "Payload data".
Certain bits and opcodes are reserved for future expansion of the
protocol.
A data frame MAY be transmitted by either the client or the server at
any time after opening …
> Data Framing support (RFC section 5)

- Sources/WebSocket/WebSocketHandler.swift
Some servers e.g. [gorilla/websocket](https://github.com/gorilla/websocket/blob/master/conn.go#L850) **close connection** and send error to this client, when receives `.pong` which is **not** masked.
from the RFC:
```
To avoid confusing network intermediaries (such as
intercepting proxies) and for security reasons that are further
discussed in Section 10.3, a client MUST mask all frames that it
sends to the server (see Section 5.3 for further details).  (Note
that masking is done whether or not the WebSocket Protocol is running
over TLS.)  The server MUST close the connection upon receiving a
frame that is not masked.
```
So we need to mask:
- Pong frames 
- Close frames - [close frames sent from client to server must be masked as per
Section …
> Masking `pong` and `close` frames 

- Sources/WebSocket/WebSocket.swift
Fix https://github.com/vapor/websocket/issues/18.
This PR sets the WebSocketFrame mask key value required by the WebSocket spec as discussed in https://github.com/vapor/websocket/issues/7
> Set WebSocketFrame's mask key parameter

- Sources/WebSocketKit/WebSocketHandler.swift
The `channelInactive` callback is triggered when a WebSocket closes without sending a close code. Previously, the `WebSocket.onClose` future was still fulfilled but `WebSocket.isClosed` would be false and `WebSocket.closeCode` would be nil. This would later cause an assertion when `WebSocket` deinitialized.  Now the `onClose` future is still fulfilled, but while also setting `isClosed` and `closeCode` (#60, fixes https://github.com/vapor/vapor/issues/2107).
> Add channelInactive callback to mark WebSocket as closed.

- Sources/WebSocketKit/WebSocket.swift
- Sources/WebSocketKit/WebSocketHandler.swift
Updates WebSocket close to send correct code to peer according to [RFC6455](https://tools.ietf.org/html/rfc6455#section-7.4) (#67).
> Send correct close code to peer

- Sources/WebSocketKit/WebSocket.swift
- Sources/WebSocketKit/WebSocketHandler.swift
Adds a `pingInterval` property on WebSocket which will trigger automatic pings to the peer to ensure that the connection is still active (#68).
> Automatic WebSocket pings

- Sources/WebSocketKit/WebSocket.swift
Resolves an issue where web socket connections weren't being closed after being sent a `close()` from the client on TLS connections (#89). Resolves (#86)
> Fix issue where web sockets don't close on TLS connections

- .gitignore
- Package.swift
- Sources/WebSocketKit/WebSocketClient.swift
Fix `TLSConfiguration.forClient()` deprecation warning
```
warning: 'forClient(cipherSuites:minimumTLSVersion:maximumTLSVersion:certificateVerification:trustRoots:certificateChain:privateKey:applicationProtocols:shutdownTimeout:keyLogCallback:)' is deprecated: renamed to 'makeClientConfiguration()'
```
> Fix deprecation in `WebSocketClient`

- Sources/WebSocketKit/HTTPInitialRequestHandler.swift
- Sources/WebSocketKit/WebSocket+Connect.swift
- Sources/WebSocketKit/WebSocketClient.swift
- Tests/WebSocketKitTests/WebSocketKitTests.swift
Prevents query parameters passed in the WebSocket URI from being silently dropped on connection (#101, fixes #94).
Calling `WebSocket.connect` with the URI `wss://localhost:443?foo=bar&bar=baz` now sends the full URI, including the query parameters, to the server.
> Persist query parameters in WebSocket URI

- Sources/WebSocketKit/WebSocket.swift
- Tests/WebSocketKitTests/WebSocketKitTests.swift
Control frames can appear in the middle of fragmented messages. Therefor they must not be part of the `frameSequence`. Also expose the frame data of the control frames, as that might be usable application data.
Before this PR, `onPing` was never called at all.
> Make sure onPing is called and account for control frames being able to be interspersed with message fragments

- Package.swift
- Sources/WebSocketKit/WebSocketClient.swift
Starting with [`SwiftNIO` 2.41.0](https://github.com/apple/swift-nio/releases/tag/2.41.0), `NIOAtomics` is deprecated in favor of `Atomics`.
This produces a warning if you use `SwiftNIO` 2.41.0 or higher.
This PR add a dependency to `Atomics` to change the only use of `NIOAtomics` to `Atomics`, and suppress the warning.
```
path/to/package/.build/checkouts/websocket-kit/Sources/WebSocketKit/WebSocketClient.swift:40:22: warning: 'NIOAtomic' is deprecated: please use ManagedAtomic from https://github.com/apple/swift-atomics instead
let isShutdown = NIOAtomic.makeAtomic(value: false)
^
```
> Remove use of NIOAtomics in favor of Atomics

- Sources/WebSocketKit/HTTPInitialRequestHandler.swift
- Tests/WebSocketKitTests/WebSocketKitTests.swift
⚠️ **WARNING**: This release removes the hard-coded `content-type` header from the upgrade request. If you were relying on this you'll need to manually add it now, but since there's no body it shouldn't be required
[Some](https://alpaca.markets/docs/api-references/trading-api/streaming/) WebSocket servers use the `Content-Type` header to determine which serialization format to use for its WebSocket messages. However, `HTTPInitialRequestHandler` [adds](https://github.com/vapor/websocket-kit/blob/62f568aa9d338aa33790534fa7b5800976f93af8/Sources/WebSocketKit/HTTPInitialRequestHandler.swift#L24) a hard-coded `Content-Type: text/plain; charset=utf-8` header to the WebSocket client’s HTTP upgrade request, so the client cannot customize the header value.
Given that the HTTP upgrade request body …
> Do not add a `Content-Type` header to the HTTP upgrade request

- .api-breakage/allowlist-branch-update-for-new-niossl.txt
- .github/workflows/main-codecov.yml
- .github/workflows/projectboard.yml
- .github/workflows/test.yml
- Package.swift
- README.md
- Sources/WebSocketKit/Concurrency/WebSocket+Concurrency.swift
- Sources/WebSocketKit/Exports.swift
- Sources/WebSocketKit/HTTPUpgradeRequestHandler.swift
- Sources/WebSocketKit/WebSocket+Connect.swift
- Sources/WebSocketKit/WebSocket.swift
- Sources/WebSocketKit/WebSocketClient.swift
- Sources/WebSocketKit/WebSocketHandler.swift
- Tests/WebSocketKitTests/AsyncWebSocketKitTests.swift
- Tests/WebSocketKitTests/SSLTestHelpers.swift
- Tests/WebSocketKitTests/Utilities.swift
- Tests/WebSocketKitTests/WebSocketKitTests.swift
Fix for [SwiftNIOSSL 2.23.1](https://github.com/apple/swift-nio-ssl/releases/tag/2.23.1) breaking the build of the WebSocket tests due to `EVP_PKEY` no longer being visible.
Shoutout and thanks to @jhoughjr for reporting the problem!
Additional changes:
- Require Swift 5.6 (matching the rest of Vapor)
- Update CI (wouldn't be an @gwynne PR without CI tweaks!)
- Enable Concurrency back-deployment
- Normalize platform support
- Some very minor code quality cleanups
- Added several missing tests (binary frames, manual pings, automatic pings, various connect methods)
> Update for new NIOSSL

- .github/workflows/test.yml
- .gitignore
- Package.swift
- Sources/WebSocketKit/Concurrency/WebSocket+Concurrency.swift
- Sources/WebSocketKit/Exports.swift
- Sources/WebSocketKit/WebSocket+Connect.swift
- Sources/WebSocketKit/WebSocket.swift
- Sources/WebSocketKit/WebSocketClient.swift
- Sources/WebSocketKit/WebSocketHandler.swift
- Tests/WebSocketKitTests/AsyncWebSocketKitTests.swift
- Tests/WebSocketKitTests/SSLTestHelpers.swift
- Tests/WebSocketKitTests/WebSocketKitTests.swift
Bump minimum Swift version to 5.6 and add Sendable conformances where appropriate
> Add Sendable conformances to WebsocketKit

- .github/workflows/test.yml
- .gitignore
- Package.swift
- Sources/WebSocketKit/Concurrency/WebSocket+Concurrency.swift
- Sources/WebSocketKit/Exports.swift
- Sources/WebSocketKit/WebSocket+Connect.swift
- Sources/WebSocketKit/WebSocket.swift
- Sources/WebSocketKit/WebSocketClient.swift
- Sources/WebSocketKit/WebSocketHandler.swift
- Tests/WebSocketKitTests/AsyncWebSocketKitTests.swift
- Tests/WebSocketKitTests/SSLTestHelpers.swift
- Tests/WebSocketKitTests/WebSocketKitTests.swift
Due to unforeseen source compatibility breakage, this backs out the changes from release 2.10.0 for now.
> Revert "Add Sendable conformances to WebsocketKit (#131)"

- .api-breakage/allowlist-branch-sendable-take-2.txt
- .github/workflows/test.yml
- .gitignore
- Package.swift
- Sources/WebSocketKit/Concurrency/WebSocket+Concurrency.swift
- Sources/WebSocketKit/Exports.swift
- Sources/WebSocketKit/WebSocket+Connect.swift
- Sources/WebSocketKit/WebSocket.swift
- Sources/WebSocketKit/WebSocketClient.swift
- Sources/WebSocketKit/WebSocketHandler.swift
- Tests/WebSocketKitTests/AsyncWebSocketKitTests.swift
- Tests/WebSocketKitTests/SSLTestHelpers.swift
- Tests/WebSocketKitTests/WebSocketKitTests.swift
Adds `Sendable` annotations where possible. This time we're using `@preconcurrency` to suppress errors in unsafe code from downstream users
> Sendable Take 2

- Package.swift
Set the minimum supported Swift version to 5.7. This is due to the usage of `@preconcurrency`
> Bump the swift-tools-version to 5.7

- Sources/WebSocketKit/Concurrency/WebSocket+Concurrency.swift
- Sources/WebSocketKit/WebSocket.swift
- Tests/WebSocketKitTests/WebSocketKitTests.swift
This PR enables access to the data in the control frames handled via `onPing`/`onPong` via a new API with the existing `onPing` and `onPong` methods being deprecated.
> Pass a copy of the control frame buffer to ping/pong callbacks

- Sources/WebSocketKit/WebSocket.swift
This allows for passing in `Data` or `ByteBufferView` to `send(_:)`, as well as the currently-supported `[UInt8]` type.
> Allow `send(_ binary:)` to accept `some DataProtocol`

- Package.swift
Recent changes make use of some methods that weren't introduced to Swift-Nio until 2.78.0, so this package will not actually compile with anything older.
> Increase minimum required version of Swift-Nio to 2.78.0
